name: aeropython36
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- ipywidgets>=6.0
- jupyter>=1.0
- notebook>=5.0
- matplotlib
- numba
- numpy
- pandas
- scipy
- xlrd
- sympy
- pip:
  - line-profiler>=2.0

